/// @description Insert description here
// You can write your code in this 
draw_self()
draw_text(0,0,"X Velocity: " + string(vx) + "Y Velocity: " + string(vy))
draw_text(0,25, "X Acc " + string(acc_x) + "Y Acc: " + string(acc_y))
draw_text(0,50, "X Sun Acc " + string(acc_sun_x) + "Y Sun Acc: " + string(acc_sun_y))
draw_text(0,75, "X Total Acc " + string(acc_x + acc_sun_x) + "Y Total Acc: " + string(acc_y + acc_sun_y))
draw_text(0,100,"X Dist from sun: " + string(sun_to_astronaut[0]) + "Y Disty from sun: " + string(sun_to_astronaut[1]) + " Length: " + string(sqrt(power(sun_to_astronaut[0],2) + power(sun_to_astronaut[1],2))))
draw_text(0,125,"Distance from sun: " + string(distance_from_sun))
draw_line(x,y, x - sun_to_astronaut[0] * 1,y - sun_to_astronaut[1] * 1)
draw_set_color(c_green)
draw_line(x,y,x + acc_x * 1000 ,y + acc_y* 1000)
draw_set_color(c_red)
draw_line(x,y,x + acc_sun_x * 1000 ,y + acc_sun_y* 1000)
draw_set_color(c_white)